"""Wavefront OBJ + MTL writer with one material (group) per print color."""
from __future__ import annotations

from pathlib import Path

import numpy as np

from ..voxel.mesher import MeshSet


def write_obj(path: str | Path, meshes: MeshSet, object_name: str = "mc-print-3d") -> list[Path]:
    path = Path(path)
    if path.suffix.lower() != ".obj":
        path = path.with_suffix(".obj")
    mtl_path = path.with_suffix(".mtl")
    lines: list[str] = [f"# {object_name} – generated by mc-print-3d", f"mtllib {mtl_path.name}", f"o {object_name}"]
    mtl: list[str] = ["# mc-print-3d materials"]
    offset = 1
    for i, m in enumerate(meshes.meshes, start=1):
        info = meshes.materials.get(m.material, {})
        name = _safe(info.get("name") or m.name or f"material_{m.material}")
        color = info.get("color", m.color)
        r, g, b = (float(c) / 255.0 for c in color[:3])
        mtl.append(f"newmtl {name}")
        mtl.append(f"Kd {r:.4f} {g:.4f} {b:.4f}")
        mtl.append(f"Ka {r * 0.2:.4f} {g * 0.2:.4f} {b * 0.2:.4f}")
        mtl.append("Ks 0.0 0.0 0.0")
        mtl.append("d 0.6" if info.get("translucent") else "d 1.0")
        mtl.append("illum 1")
        lines.append(f"g {name}")
        lines.append(f"usemtl {name}")
        v = m.vertices
        lines.extend(f"v {x:.5f} {y:.5f} {z:.5f}" for x, y, z in v.tolist())
        t = m.triangles + offset
        lines.extend(f"f {a} {b} {c}" for a, b, c in t.tolist())
        offset += len(v)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    mtl_path.write_text("\n".join(mtl) + "\n", encoding="utf-8")
    return [path, mtl_path]


def _safe(name: str) -> str:
    return "".join(ch if ch.isalnum() or ch in "-_." else "_" for ch in name)[:60] or "material"
