"""Write a complete kit: per-piece STLs, print plates (3MF with independent objects), baseplates, guide."""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Callable, Optional

import numpy as np

from ..color.quantize import ColorPlan
from ..export.stl import write_stl
from ..export.threemf import write_3mf
from ..voxel.grid import VoxelModel
from ..voxel.mesher import Mesh, MeshSet
from .guide import write_guide_html, write_parts_csv
from .layout import Plate, pack_plates
from .pieces import Kit, KitSettings, build_all_meshes, extract_pieces

log = logging.getLogger(__name__)
ProgressFn = Callable[[float, str], None]


def _safe(name: str) -> str:
    return "".join(ch if ch.isalnum() or ch in "-_" else "_" for ch in name)[:48]


def build_kit(model: VoxelModel, plan: ColorPlan, settings: KitSettings, progress: Optional[ProgressFn] = None) -> tuple[Kit, list[Plate]]:
    if progress:
        progress(0.62, "Kit: merging blocks into pieces")
    kit = extract_pieces(model, plan, settings)
    if progress:
        progress(0.66, f"Kit: building {len(kit.pieces)} piece types ({kit.total_pieces} pieces)")
    build_all_meshes(kit, model)
    if progress:
        progress(0.85, "Kit: arranging print plates")
    plates = pack_plates(kit)
    return kit, plates


def write_kit(kit: Kit, plates: list[Plate], out_dir: Path, title: str, progress: Optional[ProgressFn] = None) -> list[Path]:
    out_dir = Path(out_dir)
    pieces_dir = out_dir / "pieces"
    plates_dir = out_dir / "plates"
    pieces_dir.mkdir(parents=True, exist_ok=True)
    plates_dir.mkdir(parents=True, exist_ok=True)
    files: list[Path] = []
    # individual piece types (single solid each)
    for p in kit.pieces:
        if p.mesh is None or not p.mesh.meshes:
            continue
        name = f"{p.id}_{_safe(p.state.path)}_{p.length}x1_qty{p.count}.stl"
        files.append(write_stl(pieces_dir / name, p.mesh.merged(), header=f"mc-print-3d {p.id}"))
    plate_of: dict[str, list[int]] = {}
    for pl in plates:
        for it in pl.items:
            plate_of.setdefault(it.piece.id, [])
            if pl.index not in plate_of[it.piece.id]:
                plate_of[it.piece.id].append(pl.index)
    # plates: independent objects, pre-positioned on the bed, one filament per plate
    for i, pl in enumerate(plates):
        if progress:
            progress(0.86 + 0.1 * i / max(len(plates), 1), f"Kit: writing plate {pl.index}/{len(plates)}")
        ms = MeshSet(materials={pl.material: {"name": kit.material_info.get(pl.material, {}).get("name", f"material {pl.material}"),
                                             "color": tuple(pl.rgb), "slot": kit.material_info.get(pl.material, {}).get("slot", 1)}})
        for k, it in enumerate(pl.items):
            src = it.piece.mesh.merged()
            v = src.vertices.astype(np.float32).copy()
            v[:, 0] += np.float32(it.x)
            v[:, 1] += np.float32(it.y)
            ms.meshes.append(Mesh(pl.material, v, src.triangles, name=f"{it.piece.id} #{k + 1}", color=tuple(pl.rgb)))
        mat_name = _safe(kit.material_info.get(pl.material, {}).get("name", f"material_{pl.material}"))
        files.append(write_3mf(plates_dir / f"plate_{pl.index:02d}_{mat_name}.3mf", ms, title=f"{title} plate {pl.index}", assembly=False))
    # baseplates
    for bp in kit.baseplates:
        if bp.mesh is None or not bp.mesh.meshes:
            continue
        files.append(write_stl(out_dir / f"baseplate_{bp.id}_{bp.x1 - bp.x0}x{bp.z1 - bp.z0}.stl", bp.mesh.merged(), header="mc-print-3d baseplate"))
    files.append(write_parts_csv(kit, out_dir / "parts.csv", plate_of))
    files.append(write_guide_html(kit, plates, out_dir / "assembly_guide.html", title, plate_of))
    readme = out_dir / "README.txt"
    s = kit.settings
    readme.write_text(
        f"{title} - modular kit generated by mc-print-3d\n\n"
        f"Unit size: {s.unit_mm:g} mm per block  |  stud {s.stud_w:.1f} x {s.stud_h:.1f} mm  |  socket clearance {s.fit_tolerance_mm:.2f} mm per side\n"
        f"Pieces: {kit.total_pieces} ({len(kit.pieces)} types)  |  plates: {len(plates)}  |  baseplate tiles: {len(kit.baseplates)}\n\n"
        "pieces/   one STL per piece type, quantity in the file name\n"
        "plates/   3MF print plates, pieces already arranged on the bed, one filament per plate\n"
        "baseplate_*.stl  studded ground tiles the first layer clicks onto\n"
        "assembly_guide.html  layer-by-layer maps and the parts list (parts.csv is the same table)\n\n"
        "Print pieces as they are (stud up). PLA at 0.2 mm layers with 3 walls gives a firm clutch;\n"
        "adjust 'fit tolerance' and re-export if studs are too tight or too loose for your printer.\n",
        encoding="utf-8")
    files.append(readme)
    return files
