"""Mob geometry straight from the game.

``vanilla_models.json`` is generated by ``tools/extract_entity_models.py``, which runs the entity model
code of a client jar (``CreeperModel.createBodyLayer()`` and friends) through a small bytecode
interpreter and dumps every ``LayerDefinition``: the ``ModelPart`` tree with ``PartPose`` offsets and
rotations, each ``addBox`` with its ``texOffs``, mirror flag and ``CubeDeformation``, the texture size
the model was authored for, and the scale that ``LayerDefinitions`` applies (cave spider 0.7, wither
skeleton 1.2, ghast 4.5...).  Nothing about the shapes is written by hand here.

What this module adds is the small amount of per-mob knowledge that is not in the layer definition:
which texture the renderer uses, which layers are stacked (sheep wool, the slime's outer cube), which
parts the game hides in its default state (an armadillo's rolled-up cube, a frog's tongue) and the
few rest poses that ``setupAnim`` sets at runtime (zombie arms forward, a cat's tail).  Overlay layers
(hats, jackets, sleeves) are baked onto the body part they cover instead of being printed as
paper-thin shells.

All coordinates keep Minecraft's conventions: model units (1/16 block), **y down**, ``PartPose``
rotations in radians applied as Z·Y·X.  :mod:`mcprint.mobs.raster` reproduces the renderer's
``scale(-1, -1, 1)`` and the ``180 - yaw`` turn.
"""
from __future__ import annotations

import json
import math
from dataclasses import dataclass, field
from functools import lru_cache
from pathlib import Path
from typing import Optional

PI = math.pi

# dye order used by sheep 'Color' bytes and wool names
DYE_NAMES = ["white", "orange", "magenta", "light_blue", "yellow", "lime", "pink", "gray", "light_gray", "cyan",
             "purple", "blue", "brown", "green", "red", "black"]
DYE_RGB: dict[str, tuple[int, int, int]] = {
    "white": (0xF9, 0xFF, 0xFE), "orange": (0xF9, 0x80, 0x1D), "magenta": (0xC7, 0x4E, 0xBD),
    "light_blue": (0x3A, 0xB3, 0xDA), "yellow": (0xFE, 0xD8, 0x3D), "lime": (0x80, 0xC7, 0x1F),
    "pink": (0xF3, 0x8B, 0xAA), "gray": (0x47, 0x4F, 0x52), "light_gray": (0x9D, 0x9D, 0x97),
    "cyan": (0x16, 0x9C, 0x9C), "purple": (0x89, 0x32, 0xB8), "blue": (0x3C, 0x44, 0xAA),
    "brown": (0x83, 0x54, 0x32), "green": (0x5E, 0x7C, 0x16), "red": (0xB0, 0x2E, 0x26), "black": (0x1D, 0x1D, 0x21),
}


# ======================================================================================
# geometry containers (what the rasterizer consumes)
# ======================================================================================
@dataclass
class MobBox:
    origin: tuple[float, float, float]          # addBox x, y, z (part-relative, y down)
    size: tuple[float, float, float]            # w, h, d
    uv: tuple[float, float] = (0.0, 0.0)        # texOffs
    mirror: bool = False
    inflate: float = 0.0                        # CubeDeformation
    texture: Optional[str] = None               # override the model texture
    tint: Optional[tuple[int, int, int]] = None  # multiply (wool, slime...)
    translucent: bool = False                   # printed as the 'clear filament' color
    overlay_uv: Optional[tuple[float, float]] = None   # second skin layer baked where opaque
    overlay_texture: Optional[str] = None       # e.g. enderman eyes
    face_textures: Optional[dict] = None        # face -> (block texture resource, pixel rect or None): pumpkin heads


@dataclass
class MobPart:
    name: str
    boxes: list[MobBox] = field(default_factory=list)
    offset: tuple[float, float, float] = (0.0, 0.0, 0.0)
    rotation: tuple[float, float, float] = (0.0, 0.0, 0.0)   # radians x, y, z (PartPose)
    parent: Optional[str] = None


@dataclass
class MobModel:
    id: str
    texture: str
    parts: list[MobPart]
    scale: float = 1.0                          # renderer scale (ghast 4.5, wither skeleton 1.2, slime size...)
    tex_size: tuple[int, int] = (64, 32)        # texture size the model was authored for (HD packs scale up)
    label: str = ""
    width: float = 1.0                          # hitbox width in blocks (informational)
    height: float = 1.0
    layer: str = ""

    def part(self, name: str) -> MobPart:
        for p in self.parts:
            if p.name == name:
                return p
        raise KeyError(name)


def _box(x, y, z, w, h, d, u=0, v=0, **kw) -> MobBox:
    return MobBox((float(x), float(y), float(z)), (float(w), float(h), float(d)), (float(u), float(v)), **kw)


def _part(name, boxes, offset=(0, 0, 0), rotation=(0, 0, 0), parent=None) -> MobPart:
    return MobPart(name, list(boxes), tuple(float(v) for v in offset), tuple(float(v) for v in rotation), parent)


# ======================================================================================
# the extracted layer definitions
# ======================================================================================
_DATA_PATH = Path(__file__).with_name("vanilla_models.json")


@lru_cache(maxsize=1)
def vanilla_layers() -> dict:
    """{layer name: {'texture_size': [w, h], 'root_scale': s, 'parts': [...]}} from vanilla_models.json."""
    with open(_DATA_PATH, encoding="utf-8") as fh:
        data = json.load(fh)
    return data.get("layers", {})


OVERLAY_PART_NAMES = {"hat", "jacket", "right_sleeve", "left_sleeve", "right_pants", "left_pants", "hat_rim"}


def _layer_parts(layer: dict, *, prefix: str = "", texture: Optional[str] = None, tint=None, translucent: bool = False,
                 hidden: tuple = (), poses: Optional[dict] = None, overlays: Optional[dict] = None) -> list[MobPart]:
    """Convert one extracted layer into MobParts (hidden parts dropped, overlay layers baked)."""
    poses = poses or {}
    overlays = overlays or {}
    by_path: dict[str, MobPart] = {}
    out: list[MobPart] = []
    hidden_paths: set[str] = set()
    for p in layer["parts"]:
        path = p["path"]
        name = path.rsplit("/", 1)[-1]
        parent = p["parent"]
        if name in hidden or path in hidden or (parent and any(parent == h or parent.startswith(h + "/") for h in hidden_paths)):
            hidden_paths.add(path)
            continue
        cubes = p["cubes"]
        # overlay layer (hat / jacket / sleeves / pants): a cube of the parent's size drawn inflated over it.
        # Bake it onto that cube (or drop it when it is an inner layer); anything else named 'hat' (a witch's
        # pointed hat, a villager's brim) is real geometry and stays.
        if name in OVERLAY_PART_NAMES and parent and parent in by_path:
            host = by_path[parent]
            matched = 0
            for c in cubes:
                infl = max(c["inflate"])
                for hb in host.boxes:
                    if tuple(hb.size) == tuple(c["size"]) and tuple(hb.origin) == tuple(c["origin"]):
                        matched += 1
                        if infl > 0:
                            hb.overlay_uv = (c["uv"][0], c["uv"][1])
                            if texture:
                                hb.overlay_texture = texture
            if matched == len(cubes) and cubes:
                by_path[path] = host          # children of the overlay (a villager's hat rim) hang off the host
                continue
        rot = tuple(p["rotation"])
        if path in poses:
            rot = tuple(float(v) for v in poses[path])
        elif name in poses:
            rot = tuple(float(v) for v in poses[name])
        boxes = []
        for c in cubes:
            infl = c["inflate"]
            boxes.append(MobBox(tuple(c["origin"]), tuple(c["size"]), (c["uv"][0], c["uv"][1]), bool(c["mirror"]),
                               float(max(infl)) if max(infl) >= 0 else float(min(infl)), texture=texture, tint=tint,
                               translucent=translucent))
        for b in boxes:
            ov = overlays.get(path) or overlays.get(name)
            if ov:
                b.overlay_uv = tuple(b.uv)
                b.overlay_texture = ov
        parent_name = by_path[parent].name if parent and parent in by_path else None   # baked overlays resolve to their host
        part = MobPart(prefix + path, boxes, tuple(p["offset"]), rot, parent_name)
        by_path[path] = part
        out.append(part)
    return out


# ======================================================================================
# per-mob knowledge that is not in the layer definition
# ======================================================================================
@dataclass
class MobSpec:
    layer: str
    texture: str
    label: str = ""
    extra_layers: tuple = ()      # (layer, texture, tint, translucent)
    hidden: tuple = ()            # part names / paths hidden in the default state
    poses: dict = field(default_factory=dict)      # part -> (rx, ry, rz) from setupAnim's rest state
    overlays: dict = field(default_factory=dict)   # part -> overlay texture baked on top
    scale: float = 1.0            # renderer scale not present in the layer definition
    width: float = 0.6
    height: float = 1.8
    slim: bool = False


ZOMBIE_ARMS = {"right_arm": (-PI / 2.25, -0.1, 0.0), "left_arm": (-PI / 2.25, 0.1, 0.0)}   # AnimationUtils.animateZombieArms, idle
E = "minecraft:entity/"

REGISTRY: dict[str, MobSpec] = {
    # ---- hostile ----------------------------------------------------------------------
    "creeper": MobSpec("creeper", E + "creeper/creeper", "creeper", width=0.6, height=1.7),
    "zombie": MobSpec("zombie", E + "zombie/zombie", "zombie", poses=ZOMBIE_ARMS),
    "husk": MobSpec("husk", E + "zombie/husk", "husk", poses=ZOMBIE_ARMS),
    "drowned": MobSpec("drowned", E + "zombie/drowned", "drowned", poses=ZOMBIE_ARMS),
    "zombie_villager": MobSpec("zombie_villager", E + "zombie_villager/zombie_villager", "zombie villager", poses=ZOMBIE_ARMS),
    "giant": MobSpec("giant", E + "zombie/zombie", "giant", poses=ZOMBIE_ARMS, width=3.6, height=12.0),
    "skeleton": MobSpec("skeleton", E + "skeleton/skeleton", "skeleton"),
    "stray": MobSpec("stray", E + "skeleton/stray", "stray"),
    "bogged": MobSpec("bogged", E + "skeleton/bogged", "bogged"),
    "parched": MobSpec("parched", E + "skeleton/parched", "parched"),
    "wither_skeleton": MobSpec("wither_skeleton", E + "skeleton/wither_skeleton", "wither skeleton", width=0.7, height=2.4),
    "spider": MobSpec("spider", E + "spider/spider", "spider", width=1.4, height=0.9),
    "cave_spider": MobSpec("cave_spider", E + "spider/cave_spider", "cave spider", width=0.7, height=0.5),
    "enderman": MobSpec("enderman", E + "enderman/enderman", "enderman", overlays={"head": E + "enderman/enderman_eyes"}, height=2.9),
    "slime": MobSpec("slime", E + "slime/slime", "slime", extra_layers=(("slime_outer", E + "slime/slime", None, True),), width=1.0, height=1.0),
    "magma_cube": MobSpec("magma_cube", E + "slime/magmacube", "magma cube", width=1.0, height=1.0),
    "ghast": MobSpec("ghast", E + "ghast/ghast", "ghast", width=4.0, height=4.0),
    "happy_ghast": MobSpec("happy_ghast", E + "ghast/happy_ghast", "happy ghast", width=4.0, height=4.0),
    "blaze": MobSpec("blaze", E + "blaze", "blaze", height=1.8),
    "witch": MobSpec("witch", E + "witch", "witch", height=1.95),
    "evoker": MobSpec("evoker", E + "illager/evoker", "evoker", hidden=("right_arm", "left_arm")),
    "vindicator": MobSpec("vindicator", E + "illager/vindicator", "vindicator", hidden=("right_arm", "left_arm")),
    "pillager": MobSpec("pillager", E + "illager/pillager", "pillager", hidden=("right_arm", "left_arm")),
    "illusioner": MobSpec("illusioner", E + "illager/illusioner", "illusioner", hidden=("right_arm", "left_arm")),
    "ravager": MobSpec("ravager", E + "illager/ravager", "ravager", width=1.95, height=2.2),
    "vex": MobSpec("vex", E + "illager/vex", "vex", width=0.4, height=0.8),
    "piglin": MobSpec("piglin", E + "piglin/piglin", "piglin"),
    "piglin_brute": MobSpec("piglin_brute", E + "piglin/piglin_brute", "piglin brute"),
    "zombified_piglin": MobSpec("zombified_piglin", E + "piglin/zombified_piglin", "zombified piglin"),
    "hoglin": MobSpec("hoglin", E + "hoglin/hoglin", "hoglin", width=1.4, height=1.4),
    "zoglin": MobSpec("zoglin", E + "hoglin/zoglin", "zoglin", width=1.4, height=1.4),
    "guardian": MobSpec("guardian", E + "guardian", "guardian", width=0.85, height=0.85),
    "elder_guardian": MobSpec("elder_guardian", E + "guardian_elder", "elder guardian", width=2.0, height=2.0),
    "shulker": MobSpec("shulker", E + "shulker/shulker", "shulker", width=1.0, height=1.0),
    "silverfish": MobSpec("silverfish", E + "silverfish", "silverfish", width=0.4, height=0.3),
    "endermite": MobSpec("endermite", E + "endermite", "endermite", width=0.4, height=0.3),
    "phantom": MobSpec("phantom", E + "phantom", "phantom", width=0.9, height=0.5),
    "warden": MobSpec("warden", E + "warden/warden", "warden", width=0.9, height=2.9),
    "breeze": MobSpec("breeze", E + "breeze/breeze", "breeze", width=0.6, height=1.77),
    "creaking": MobSpec("creaking", E + "creaking/creaking", "creaking", width=0.9, height=2.7),
    "strider": MobSpec("strider", E + "strider/strider", "strider", width=0.9, height=1.7),
    # ---- friendly ---------------------------------------------------------------------
    "player": MobSpec("player", E + "player/wide/steve", "player (Steve)"),
    "player_slim": MobSpec("player_slim", E + "player/slim/alex", "player (Alex, slim)", slim=True),
    "villager": MobSpec("villager", E + "villager/villager", "villager", height=1.95),
    "wandering_trader": MobSpec("wandering_trader", E + "wandering_trader", "wandering trader", height=1.95),
    "iron_golem": MobSpec("iron_golem", E + "iron_golem/iron_golem", "iron golem", width=1.4, height=2.7),
    "snow_golem": MobSpec("snow_golem", E + "snow_golem", "snow golem", width=0.7, height=1.9),
    "allay": MobSpec("allay", E + "allay/allay", "allay", width=0.35, height=0.6),
    "pig": MobSpec("pig", E + "pig/temperate_pig", "pig", width=0.9, height=0.9),
    "cow": MobSpec("cow", E + "cow/temperate_cow", "cow", width=0.9, height=1.4),
    "mooshroom": MobSpec("mooshroom", E + "cow/red_mooshroom", "mooshroom", width=0.9, height=1.4),
    "sheep": MobSpec("sheep", E + "sheep/sheep", "sheep", extra_layers=(("sheep_wool", E + "sheep/sheep_wool", DYE_RGB["white"], False),), width=0.9, height=1.3),
    "chicken": MobSpec("chicken", E + "chicken/temperate_chicken", "chicken", width=0.4, height=0.7),
    "wolf": MobSpec("wolf", E + "wolf/wolf", "wolf", width=0.6, height=0.85),
    "cat": MobSpec("cat", E + "cat/tabby", "cat", poses={"tail2": (1.7278761, 0.0, 0.0)}, width=0.6, height=0.7),
    "ocelot": MobSpec("ocelot", E + "cat/ocelot", "ocelot", poses={"tail2": (1.7278761, 0.0, 0.0)}, width=0.6, height=0.7),
    "horse": MobSpec("horse", E + "horse/horse_brown", "horse", width=1.4, height=1.6),
    "skeleton_horse": MobSpec("skeleton_horse", E + "horse/horse_skeleton", "skeleton horse", width=1.4, height=1.6),
    "zombie_horse": MobSpec("zombie_horse", E + "horse/horse_zombie", "zombie horse", width=1.4, height=1.6),
    "llama": MobSpec("llama", E + "llama/creamy", "llama", hidden=("right_chest", "left_chest"), width=0.9, height=1.87),
    "panda": MobSpec("panda", E + "panda/panda", "panda", width=1.3, height=1.25),
    "fox": MobSpec("fox", E + "fox/fox", "fox", width=0.6, height=0.7),
    "goat": MobSpec("goat", E + "goat/goat", "goat", width=0.9, height=1.3),
    "rabbit": MobSpec("rabbit", E + "rabbit/brown", "rabbit", width=0.4, height=0.5),
    "parrot": MobSpec("parrot", E + "parrot/parrot_red_blue", "parrot", width=0.5, height=0.9),
    "turtle": MobSpec("turtle", E + "turtle/big_sea_turtle", "turtle", width=1.2, height=0.4),
    "dolphin": MobSpec("dolphin", E + "dolphin", "dolphin", width=0.9, height=0.6),
    "squid": MobSpec("squid", E + "squid/squid", "squid", width=0.8, height=0.8),
    "glow_squid": MobSpec("glow_squid", E + "squid/glow_squid", "glow squid", width=0.8, height=0.8),
    "bee": MobSpec("bee", E + "bee/bee", "bee", width=0.7, height=0.6),
    "axolotl": MobSpec("axolotl", E + "axolotl/axolotl_lucy", "axolotl", width=0.75, height=0.42),
    "frog": MobSpec("frog", E + "frog/temperate_frog", "frog", hidden=("croaking_body", "tongue"), width=0.5, height=0.5),
    "tadpole": MobSpec("tadpole", E + "tadpole/tadpole", "tadpole", width=0.4, height=0.3),
    "camel": MobSpec("camel", E + "camel/camel", "camel", width=1.7, height=2.375),
    "sniffer": MobSpec("sniffer", E + "sniffer/sniffer", "sniffer", width=1.9, height=1.75),
    "armadillo": MobSpec("armadillo", E + "armadillo", "armadillo", hidden=("cube",), width=0.7, height=0.65),
    "bat": MobSpec("bat", E + "bat", "bat", width=0.5, height=0.9),
    "cod": MobSpec("cod", E + "fish/cod", "cod", width=0.5, height=0.3),
    "salmon": MobSpec("salmon", E + "fish/salmon", "salmon", width=0.7, height=0.4),
    "pufferfish": MobSpec("pufferfish_big", E + "fish/pufferfish", "pufferfish", width=0.7, height=0.7),
    "nautilus": MobSpec("nautilus", E + "nautilus/nautilus", "nautilus", width=1.0, height=1.0),
}

MOB_IDS = sorted(REGISTRY)

# legacy / alias entity ids -> registry ids
ALIASES = {
    "villagergolem": "iron_golem", "snowman": "snow_golem", "ozelot": "cat", "mushroomcow": "mooshroom",
    "pigzombie": "zombified_piglin", "zombie_pigman": "zombified_piglin", "steve": "player", "alex": "player_slim",
    "cavespider": "cave_spider", "witherskeleton": "wither_skeleton", "irongolem": "iron_golem", "lavaslime": "magma_cube",
    "entityhorse": "horse", "skeletonhorse": "skeleton_horse", "zombiehorse": "zombie_horse",
    "pufferfish_big": "pufferfish", "trader_llama": "llama", "illager": "pillager",
}

_VARIANT_TEXTURES: dict[str, dict[str, str]] = {
    "pig": {"temperate": E + "pig/temperate_pig", "cold": E + "pig/cold_pig", "warm": E + "pig/warm_pig"},
    "cow": {"temperate": E + "cow/temperate_cow", "cold": E + "cow/cold_cow", "warm": E + "cow/warm_cow"},
    "chicken": {"temperate": E + "chicken/temperate_chicken", "cold": E + "chicken/cold_chicken", "warm": E + "chicken/warm_chicken"},
    "frog": {"temperate": E + "frog/temperate_frog", "cold": E + "frog/cold_frog", "warm": E + "frog/warm_frog"},
    "wolf": {k: E + "wolf/" + v for k, v in {"pale": "wolf", "ashen": "wolf_ashen", "black": "wolf_black", "chestnut": "wolf_chestnut",
                                              "rusty": "wolf_rusty", "snowy": "wolf_snowy", "spotted": "wolf_spotted", "striped": "wolf_striped",
                                              "woods": "wolf_woods"}.items()},
    "cat": {k: E + "cat/" + k for k in ("tabby", "black", "red", "siamese", "british_shorthair", "calico", "persian", "ragdoll", "white", "jellie", "all_black")},
    "axolotl": {k: E + "axolotl/axolotl_" + k for k in ("lucy", "wild", "gold", "cyan", "blue")},
    "rabbit": {k: E + "rabbit/" + k for k in ("brown", "white", "black", "white_splotched", "gold", "salt", "toast", "caerbannog")},
    "horse": {k: E + "horse/horse_" + k for k in ("white", "creamy", "chestnut", "brown", "black", "gray", "darkbrown")},
    "parrot": {k: E + "parrot/parrot_" + k for k in ("red_blue", "blue", "green", "yellow_blue", "grey")},
    "llama": {k: E + "llama/" + k for k in ("creamy", "white", "brown", "gray")},
    "fox": {"red": E + "fox/fox", "snow": E + "fox/snow_fox"},
    "shulker": {**{k: E + "shulker/shulker_" + k for k in DYE_NAMES}, "default": E + "shulker/shulker"},
    "mooshroom": {"red": E + "cow/red_mooshroom", "brown": E + "cow/brown_mooshroom"},
    "panda": {k: E + "panda/" + v for k, v in {"normal": "panda", "lazy": "lazy_panda", "worried": "worried_panda", "playful": "playful_panda",
                                                "brown": "brown_panda", "weak": "weak_panda", "aggressive": "aggressive_panda"}.items()},
}
# variant names that also switch to a variant-specific layer (1.21.5 cold / warm animals)
_VARIANT_LAYERS = {("cow", "cold"): "cold_cow", ("cow", "warm"): "warm_cow", ("pig", "cold"): "cold_pig", ("chicken", "cold"): "cold_chicken"}


def normalize_mob_id(raw: str) -> str:
    s = str(raw).strip().lower()
    if ":" in s:
        s = s.split(":", 1)[1]
    s = s.replace(" ", "_")
    return ALIASES.get(s, s)


# ======================================================================================
# extras that the game draws with separate renderer layers
# ======================================================================================
_PUMPKIN = {
    "north": ("minecraft:block/carved_pumpkin", None), "south": ("minecraft:block/pumpkin_side", None),
    "west": ("minecraft:block/pumpkin_side", None), "east": ("minecraft:block/pumpkin_side", None),
    "up": ("minecraft:block/pumpkin_top", None), "down": ("minecraft:block/pumpkin_top", None),
}
_MUSHROOM_TEX = "minecraft:block/red_mushroom"
_CAP_RECT = (5, 4, 11, 8)
_STEM_RECT = (7, 10, 9, 14)


def _mushroom(name: str, base, parent: Optional[str] = None) -> MobPart:
    """A red mushroom standing on ``base`` (model space): 2x5x2 stem under a 6x4x6 cap (solid, unlike the
    game's crossed cut-out planes, which are one voxel thin and slice through the head)."""
    faces = ("top", "bottom", "north", "south", "west", "east")
    cap = {f: (_MUSHROOM_TEX, _CAP_RECT) for f in faces}
    stem = {f: (_MUSHROOM_TEX, _STEM_RECT) for f in faces}
    return _part(name, [_box(-1, -5, -1, 2, 5, 2, 0, 0, face_textures=stem), _box(-3, -9, -3, 6, 4, 6, 0, 0, face_textures=cap)], base, (0, 0, 0), parent)


def _apply_extras(mid: str, model: MobModel, props: dict) -> None:
    if mid == "snow_golem":
        # SnowGolemHeadLayer: carved pumpkin block scaled 0.625 (10 units) around the snow head
        model.parts.append(_part("pumpkin", [_box(-5, -5, -5, 10, 10, 10, 0, 0, face_textures=_PUMPKIN)], (0, -1.5, 0)))
    elif mid == "mooshroom":
        # MushroomCowMushroomLayer: two mushrooms on the back, one on the head
        model.parts.append(_mushroom("back_mushroom_1", (3.2, 2.0, 7.0)))
        model.parts.append(_mushroom("back_mushroom_2", (-2.5, 2.0, -1.0)))
        model.parts.append(_mushroom("head_mushroom", (0.0, -4.0, -3.0), parent="head"))


# ======================================================================================
# build
# ======================================================================================
def mob_model(mob_id: str, props: Optional[dict] = None) -> Optional[MobModel]:
    """Build the model for an entity id (``minecraft:creeper``, ``Creeper``...) with optional NBT-derived
    properties: ``color`` (sheep), ``sheared``, ``size`` (slime / magma cube), ``variant`` (pig, cow,
    chicken, wolf, cat, frog, axolotl, rabbit, horse, parrot, llama, fox, shulker, panda), ``texture``
    (override resource) and ``slim`` (player)."""
    props = props or {}
    mid = normalize_mob_id(mob_id)
    if mid == "player" and props.get("slim"):
        mid = "player_slim"
    spec = REGISTRY.get(mid)
    if spec is None:
        return None
    layers = vanilla_layers()
    layer_name = spec.layer
    variant = str(props.get("variant", "")).split(":")[-1]
    if variant and (mid, variant) in _VARIANT_LAYERS and _VARIANT_LAYERS[(mid, variant)] in layers:
        layer_name = _VARIANT_LAYERS[(mid, variant)]
    layer = layers.get(layer_name)
    if layer is None:
        return None
    texture = spec.texture
    if variant and mid in _VARIANT_TEXTURES and variant in _VARIANT_TEXTURES[mid]:
        texture = _VARIANT_TEXTURES[mid][variant]
    if props.get("texture"):
        texture = str(props["texture"])
    parts = _layer_parts(layer, hidden=spec.hidden, poses=spec.poses, overlays=spec.overlays)
    scale = float(layer.get("root_scale", 1.0)) * spec.scale
    if mid in ("slime", "magma_cube"):
        scale *= float(max(1, int(props.get("size", 1)) + 1))
    model = MobModel(mid, texture, parts, scale=scale, tex_size=tuple(layer["texture_size"]), label=spec.label or mid.replace("_", " "),
                     width=spec.width * scale, height=spec.height, layer=layer_name)
    for extra_layer, extra_tex, tint, translucent in spec.extra_layers:
        if mid == "sheep":
            if props.get("sheared"):
                continue
            color = props.get("color", "white")
            if isinstance(color, int) or (isinstance(color, str) and color.isdigit()):
                color = DYE_NAMES[int(color) % 16]
            tint = DYE_RGB.get(str(color), DYE_RGB["white"])
        lay = layers.get(extra_layer)
        if lay is None:
            continue
        extra_parts = _layer_parts(lay, prefix=extra_layer + ":", texture=extra_tex, tint=tint, translucent=translucent)
        if translucent:
            model.parts[:0] = extra_parts        # stamped first so the opaque core and eyes stay visible inside the shell
        else:
            model.parts.extend(extra_parts)
    _apply_extras(mid, model, props)
    return model


__all__ = ["MobBox", "MobPart", "MobModel", "MobSpec", "REGISTRY", "MOB_IDS", "ALIASES", "DYE_NAMES", "DYE_RGB",
           "mob_model", "normalize_mob_id", "vanilla_layers"]
